GRANT EXECUTE ON SFO2.REP_STAT_UTIL TO SFO2_ONLINE, SFO2_BATCH;
GRANT EXECUTE ON SFO2.NLS_REP_STAT TO SFO2_ONLINE, SFO2_BATCH;
GRANT EXECUTE ON SFO2.SFS_REP_STAT TO SFO2_ONLINE, SFO2_BATCH;
GRANT EXECUTE ON SFO2.RAF_REP_STAT TO SFO2_ONLINE, SFO2_BATCH;

GRANT DEBUG ON SFO2.REP_STAT_UTIL TO SFO2_ONLINE, SFO2_BATCH, SFO2_READONLY_SA;
GRANT DEBUG ON SFO2.NLS_REP_STAT TO SFO2_ONLINE, SFO2_BATCH, SFO2_READONLY_SA;
GRANT DEBUG ON SFO2.SFS_REP_STAT TO SFO2_ONLINE, SFO2_BATCH, SFO2_READONLY_SA;
GRANT DEBUG ON SFO2.RAF_REP_STAT TO SFO2_ONLINE, SFO2_BATCH, SFO2_READONLY_SA;